call plug#begin()
let g:rustfmt_autosave = 1
"List your plugins here
Plug 'tpope/vim-sensible'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'lifepillar/vim-mucomplete'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'rust-lang/rust.vim'
Plug 'fladson/vim-kitty'  
Plug 'preservim/nerdtree'
"Plug 'vim-syntastic/syntastic'
Plug 'sts10/vim-pink-moon'
Plug 'tpope/vim-fugitive'
Plug 'junegunn/gv.vim'
Plug 'catppuccin/vim', { 'as': 'catppuccin' }
"Plug 'ervandew/supertab'
call plug#end()
syntax enable
filetype plugin indent on
set completeopt+=menuone
  set completeopt+=noinsert
  let g:mucomplete#enable_auto_at_startup = 1

"  set statusline+=%#warningmsg#
"set statusline+=%{SyntasticStatuslineFlag()}
"set statusline+=%*

"let g:syntastic_always_populate_loc_list = 1
"let g:syntastic_auto_loc_list = 1
"let g:syntastic_check_on_open = 1
"let g:syntastic_check_on_wq = 1
inoremap " ""<left>
inoremap '' ''
inoremap ' ''<left>
inoremap "" ""
inoremap ( ()<left>
inoremap () ()
inoremap [ []<left>
inoremap [] []
inoremap {<cr> {}<left><cr><cr><up><left>	
inoremap { {}<left>
inoremap {} {}
set number
set termguicolors
set background=dark
colorscheme catppuccin_macchiato	
inoremap <expr> <tab> coc#pum#visible() ? coc#pum#confirm() : "\<TAB>"
" Start NERDTree and leave the cursor in it.
autocmd VimEnter * NERDTree
