call plug#begin()
let g:rustfmt_autosave = 1
"List your plugins here
Plug 'tpope/vim-sensible'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'mhinz/vim-startify'
Plug 'junegunn/fzf.vim'
Plug 'junegunn/rainbow_parentheses.vim'
"Plug 'lifepillar/vim-mucomplete'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'rust-lang/rust.vim'
Plug 'fladson/vim-kitty'
Plug 'preservim/nerdtree'
"Plug 'vim-syntastic/syntastic'
Plug 'sts10/vim-pink-moon'
Plug 'tpope/vim-fugitive'
Plug 'junegunn/gv.vim'
Plug 'catppuccin/vim', { 'as': 'catppuccin' }
Plug 'wfxr/minimap.vim', {'do': ':!cargo install --locked code-minimap'}
Plug 'ntpeters/vim-better-whitespace'
"Plug 'ervandew/supertab'
call plug#end()
syntax enable
filetype plugin indent on
let g:better_whitespace_guicolor='#f6c177'

inoremap " ""<left>
inoremap '' ''
inoremap ' ''<left>
inoremap "" ""
inoremap ( ()<left>
inoremap () ()
inoremap [ []<left>
inoremap [] []
inoremap {<cr> {}<left><cr><cr><up><left>
inoremap { {}<left>
inoremap {} {}
inoremap < <><left>
inoremap <> <>
set number
set termguicolors
set background=dark
colorscheme catppuccin_macchiato	
inoremap <expr> <tab> coc#pum#visible() ? coc#pum#confirm() : "\<TAB>"
" Start NERDTree and leave the cursor in it.
autocmd VimEnter * NERDTree
let g:minimap_width = 10
let g:minimap_auto_start = 1
let g:minimap_auto_start_win_enter = 1
